### ISSUE TITLE
Come up with model for dignity/office data

### ISSUE THREAD

**Issue by tla** [erc-releven/.github#16]
https://docs.google.com/spreadsheets/d/1kxxXolW9EHl8Uew3mHXKllQvPhVIW9XAhUa2jjZbdpg/edit#gid=0

**Comment by Aaleks93** [comment]
I finished entering Yes/No/Civil/Clerical into the C12/C2 social categories.

**Comment by laletuver1** [comment]
tara and lale will implement this on wisski

**Comment by tla** [comment]
These changes are now reflected in the GraphDB database. We still need to decide, on a case by case basis, what to do about the following labels: 

- "Gambros of the emperor", 
- "Man", 
- "Bedroom attendant", 
- "Sorceress", 
- "Eutychestate", 
- "Hegoumenos (former)"?

**Comment by martonrozsa88** [comment]
- Gambros of the emperor: C2
- Man: C12
- Bedroom attendant: C2
- Sorceress: C2
- Eutychestate: C2
- Hegoumenos: (former): C2

**Comment by martonrozsa88** [comment]
Gambros of the emperor: gambros means a relative by marriage in general, but mostly denotes a son-in-law; the gambros of the emperor became a court title in the reign of Manuel I (way after the period of our interest), and it is only used once (on a lead seal) by Michael 136 in the eleventh century; this case suggests only representative use; the term is essentially just about kinship in our period (neither C2 nor C12).

Man: according to my querry with mysql, this term occurs in this pure form in the dataset of PBW, but it is used only in phrases like "man of the emperor" in PBW 2016; perhaps the simple designation "man" occurs in PBW 2011, but I cannot check it at the moment (the PBW website is unavailable since Monday, 29th January); the phrases such as "man of the emperor", "man of the doux" or "man of the patriarch" are equivalent with similar designations with the terms servant (e. g. "servant of the emperor") and oikeios ("oikeios of the emperor"), and the latter two are considered as social roles (C12).

Bedroom attendant: there is a case from the eleventh century; the Alexiad is the source; apparently this term is just a descriptive designation for a maiden who was present in the tent of the emperor when an attempt of assassination was made; the source itself does not use any term, which can be specifically translated to "bedroom attendant", it is an interpretation by the researcher of PBW. I think it can be C2 at best, but it apparently was just a temporary task for an unknown lady, so we can remove this designation from the dataset.

Sorceress: I found only one case (Anonyma 157) mentioned by Aristakes; Aristakes actually recites a story of an evil man who visited a sorceress in Thessalonike, so there is not much about the sorceress herself, but we can categorise this term as a social quality (C2).

Eutychestate: the term means the most blessed/most fortunate, and there is only one case of this desgnation, Maria Skleraina (Maria 64), a concubine of Constantine IX; the source of this case is a lead seal of a logothetes of the palace of Maria Skleraina, which refers to Maria as "hyperperilampros and eutychestate sebaste"; sebaste is the court title of Maria (which gave her authority), hyperperilampros and eutychestate are purely honorific and here they are seemingly just complements to the title of sebaste; therefore, I am not sure if we should include eutychestate in the database, but it does not seems either C2 or C12.

Hegoumenos (former): this term explicitly appears in a case, which belongs to the 12th century; the source use the term apoegoumenos, which can be interpreted as a separate title, but it does not matter due to the late date of the affair (1107); the source, an official document, does not imply when the former hegoumenos was the leader of his monastery; there is another case though, where the PBW uses the term "Ex-hegoumenos" for Anonymus 2392; the source is a letter from Psellos to Michael Keroullarios; Psellos actually refers to him as "once a hegoumenos", so it would be better to record this person as hegoumenos instead of a separate title, ex-hegoumenos, which has no significance in the affair described in the letter.

**Comment by tla** [comment]
Thanks @martonrozsa88 ! I have resolved these as follows:

- Removed the designations 'Gambros of the emperor', 'Eutychestate', and 'Hegoumenos (former)' from the database
- Removed the relevant assertions entirely from Michael Taronites and Maria Skleraina
- Changed the assertion concerning Antonios the former hegoumenous to simply 'Hegoumenos'.
- Retained the other two as C2 (I think the "bedroom attendant" one is no less flimsy a designation than many of the other things that PBW classed as an occupation.)

This leaves the 'Man' issue. I managed to get to PBW via Chrome (Firefox won't let me), and the two people in question are Anonymus 2392 (possibly Leon Paraspondylos) who is a "man of Keroularios", and Anonymus 2458 who is a "man of Katakalon Kekaumenos". I take both of these to be more of a social relation than a standalone social status in this context, but I'm less sure about the second one. I attach the two PBW screenshots; what do you think?

![Image](https://github.com/erc-releven/.github/assets/422052/d8c6aa71-6a58-4aed-9fa7-4070b25184ad)

![Image](https://github.com/erc-releven/.github/assets/422052/866ad3d6-644f-4178-9508-ac68b9175484)

**Comment by Aaleks93** [comment]
These two are not the same, that is, they are literally not both "a man of", but they can be modelled like that; they should, in my opinion, be C2 (social status) but definitely not C12 (a standalone social status). Here's my argumentation:
- regarding Anonymus 2392 (most probably Leon Paraspondylos) translated as "man of Keroularios" is δοῦλος, which means "slave" or "servant", but in the context of Psellos' letters it is a common term designating someone who is at the addressee's disposal, cf. "καὶ δοῦλος σός / φίλος μὲν ἐμός, δοῦλος δὲ σὸς ὁ ἀνήρ" (no. 49 in the new Papaioannou's edition, S 63 in the old), translated as "the *client* of [kaisar Ioannes]" in Lauxtermann & Jeffreys 2017, 47. Psellos calls himself many times a "servant" (usually because of doing some favor) of his addressee: "Πάλιν ὁ δοῦλος σου δεξιοῦμαί σε" (Papaioannou 81, S 48), ἰχθύας ἀφώνους ὁ δοῦλός σου πέπομφα (Papaioannou 83, S 104). And this is confirmed by Psellos himself as one of his many epithets in letters: "ὁ σὸς πρωτοπρόεδρος, φίλος, ἀδελφός, δοῦλος, διδάσκαλος" (Papaioannou 131). All this was probably taken from II Reg. 9,8 "Τίς εἰμι ὁ δοῦλός σου". In any case, this is definitely C2 and not an official position, so "a man of" would be a good translation.
- regarding Anonymus 2458 who is a "man of Katakalon Kekaumenos", now literally a "man of" ἄνθρωπός σου, is also not a C12 but C2, as it also designates a person doing a favor for someone else.
So yes, "a man of" should definitely be only C2.

**Comment by tla** [comment]
Thanks @Aaleks93 - I agree that they are definitely not C12. My question is, should they even be C2, or do they designate a social *relationship*, which should be modelled entirely differently? The "social quality" / "social role" vocabulary is meant to categorize people with respect to society at large, rather than categorizing them with respect to specific other people; the latter would be a social relationship, to be modelled with a structure kind of like how we model kinship.

**Comment by Aaleks93** [comment]
@tla I see now. Well in that case I think they are not C2 either, "a man of" in this case is like "spiritual brother", i. e., social relationship similar to kinship.

**Comment by martonrozsa88** [comment]
I hesitated about the designation of 'man', because I remembered from my PHD studies that it had relation to authority. So I supported its classification as C12 in general. However, there were few cases, where I was not sure about the categorisation. These were the examples Tara has mentioned.

I made a quick check of the secondary literature, and the picture became a bit more confusing to me. It seems that the use of the "man of the emperor" appeared on seals only around the middle of the 11th century (and maybe it is true for the official documents as well). Cheynet stresses that this was an official use of this title and the emperor supplied the official with his imperial authority in this way. In such a case, the designation was specifically used when the official had to deal with an affair. However, none of the studies I have found deals with the "men" of other potentates (kaisares, doukes, metropolitans etc.). The PBW includes some of this kind as well. This is all about the use of these terms on seals and official documents, there was, of course, a colloquial meaning as Psellos' letters show.

We can use the "man of" titles as social relations in general, especially beacuse it is not clear that "man of the doux" or "man of the metropolitan" etc. on seals and in official documents had the same function as the "man of the emperor". We can also think about the question whether we handle the "man of the emperor" as a C12 category separately from the other similar titles (since it is related to authority), or we just label it as social relation as well.

**Comment by tla** [comment]
I've had another look at this; what needs to happen is that most of these "man of the X" designations should all be converted into relationships (the same modeling path as kinship). This will need to be done with a spreadsheet and a script, since we have to see in all cases whether we can identify the person who is X. If any of them turn out to actually be an office (e.g. a "man of the patriarch" who is a servant / client of whichever patriarch is in office), then they should stay as C12.

**Comment by readl97** [comment]
https://docs.google.com/spreadsheets/d/1It3tETiS0MyBbmvApAr-DEJY3vwWoVZRGYKxIPJsQQo/edit#gid=865937189 
All done

**Comment by laletuver1** [comment]
Implementation phase.

**Comment by tla** [comment]
This query gets the sets of records that need to be deleted. Once the deletion is done, we can re-add the information as social relationships via WissKI, then this issue can be closed.

```
PREFIX star: <https://r11.eu/ns/star/>
PREFIX sdhss: <https://r11.eu/ns/prosopography/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
SELECT * WHERE {
    ?s a sdhss:C12 ;
       crm:P1_is_identified_by ?lbl .
    ?a1 a star:E13_sdhss_P33 ;
       crm:P140_assigned_attribute_to ?role ;
       crm:P141_assigned ?s ;
       crm:P14_carried_out_by ?auth ;
       crm:P17_was_motivated_by ?src .
    ?a2 a star:E13_sdhss_P26 ;
       crm:P140_assigned_attribute_to ?role ;
       crm:P141_assigned ?person ;
       crm:P14_carried_out_by ?auth ;
       crm:P17_was_motivated_by ?src .
    ?iass a crm:E15_Identifier_Assignment ;
       crm:P140_assigned_attribute_to ?person ;
       crm:P37_assigned ?pbwid .
    ?pbwid crm:P190_has_symbolic_content ?pbwname .
    FILTER(CONTAINS(?lbl, "Man of"))
    VALUES ?pbwname {
"Anonymus 14147"
"Christophoros 108"
"Eugenios 104"
"Eustathios 118"
"Ioannes 182"
"Ioannes 497"
"Ioannikios 102"
"Konstantinos 227"
"Leon 172"
"Michael 162"
"Nikolaos 226"
"Stephanos 116"
    }
} 
```

**Comment by tla** [comment]
Deletion is done with the following query, which removed 144 triples (12 rows * 2 assertions * 6 triples per assertion):

```
PREFIX data: <https://r11.eu/rdf/resource/>
PREFIX star: <https://r11.eu/ns/star/>
PREFIX sdhss: <https://r11.eu/ns/prosopography/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
WITH data:
DELETE {
    ?a1 a star:E13_sdhss_P33 ;
       crm:P140_assigned_attribute_to ?role ;
       crm:P141_assigned ?s ;
       crm:P14_carried_out_by ?auth ;
       crm:P17_was_motivated_by ?src ;
       <neo4j://graph.schema#uuid> ?uu1 .
    ?a2 a star:E13_sdhss_P26 ;
       crm:P140_assigned_attribute_to ?role ;
       crm:P141_assigned ?person ;
       crm:P14_carried_out_by ?auth ;
       crm:P17_was_motivated_by ?src ;
       <neo4j://graph.schema#uuid> ?uu2 .   
}
WHERE {
    ?s a sdhss:C12 ;
       crm:P1_is_identified_by ?lbl .
    ?a1 a star:E13_sdhss_P33 ;
       crm:P140_assigned_attribute_to ?role ;
       crm:P141_assigned ?s ;
       crm:P14_carried_out_by ?auth ;
       crm:P17_was_motivated_by ?src ;
       <neo4j://graph.schema#uuid> ?uu1 .
    ?a2 a star:E13_sdhss_P26 ;
       crm:P140_assigned_attribute_to ?role ;
       crm:P141_assigned ?person ;
       crm:P14_carried_out_by ?auth ;
       crm:P17_was_motivated_by ?src ;
       <neo4j://graph.schema#uuid> ?uu2 .
    ?iass a crm:E15_Identifier_Assignment ;
       crm:P140_assigned_attribute_to ?person ;
       crm:P37_assigned ?pbwid .
    ?pbwid crm:P190_has_symbolic_content ?pbwname .
    FILTER(CONTAINS(?lbl, "Man of"))
    VALUES ?pbwname {
"Anonymus 14147"
"Christophoros 108"
"Eugenios 104"
"Eustathios 118"
"Ioannes 182"
"Ioannes 497"
"Ioannikios 102"
"Konstantinos 227"
"Leon 172"
"Michael 162"
"Nikolaos 226"
"Stephanos 116"
    }
} 
```
