### ISSUE TITLE
Reliable way to delete assertions cleanly

### ISSUE THREAD

**Issue by tla** [erc-releven/.github#31]
Especially given the fact that WissKI has only incomplete models of many of the assertion structures, at the moment it takes some hacking around in the graph database in order to delete assertions that we have decided we don't want to keep in their exported form (cf. issue #16 .) We should decide and implement a good way to handle this.

**Comment by lu-pl** [comment]
SHACL support for GraphDB: https://graphdb.ontotext.com/documentation/10.2/shacl-validation.html

"A repository with SHACL validation must be created from scratch, i.e., Create new. You cannot modify an already existing repository by enabling the validation afterwards."

The current RELEVEN repo does *not* have SHACL validation activated. So we might have to dump the store and set up a new repo with SHACL validation enabled.

**Comment by lu-pl** [comment]
Note: I think there are generally two modes of deletion from a triple store: 

1. deleting subjects only; since RDF cannot have "dangling" predicates or objects, predicates and *literal* objects connected to a deleted subject would be deleted ("unbound") as well. I think this is what we want.

2. deleting *node closures*, i.e. walking the entire subgraph of a node and recursively deleting any nodes and edges adjacent to that node. I think this can be pretty dangerous and harder to reason about, especially with CRM/E13 data.

SPARQL DELETE operations delete *graph patterns* from a graph, which corresponds to the subjects-only deletion approach. [Delete/insert operations](https://www.w3.org/TR/sparql11-update/#deleteInsert) are a general update pattern for deleting  + inserting with the bindings of the deleted pattern still in scope.

**Comment by laletuver1** [comment]
Another discussion is necessary to determine what deletion should look like, and whether SPARQL or another program could be used to delete assertions. The issue might be revisited in July.
