### ISSUE TITLE
Spreadsheet Template for the Paths

### ISSUE THREAD

**Issue by laletuver1** [erc-releven/.github#46]

**Comment by tla** [comment]
Here is a first version for the spreadsheet template - I haven't implemented Attacks / Social Places because I'm waiting for the paths to be better nailed down, but the other things we've talked about should be there. If something is missing please let me know.
[assertion_template.xlsx](https://github.com/user-attachments/files/17535724/assertion_template.xlsx)

**Comment by tla** [comment]
Here is a second version, with the changes we agreed to last Wednesday plus a new pair of tabs 'Relationship Type' and 'Social Relationship.
[assertion_template_MASTER.xlsx](https://github.com/user-attachments/files/17703053/assertion_template_MASTER.xlsx)
